### ISSUE TITLE
Heroku Deployment

### ISSUE THREAD

**Issue by ashutoshkrris** [vgalin/html2image#24] opened 2021-06-07 14:02 UTC
How to deploy Django project that uses this package to take screenshots on Heroku?
It throws error that it cannot find Google Chrome.
Can you please help if it can be used on Heroku? @vgalin

**Comment by vgalin** [comment] 2021-06-07 23:28
Hello, I'm not really a power-user of Heroku so I won't be able to give you precise directions about how to proceed.

In a general way, you'll have to be sure that Chrome/Chromium is installed on the machine you're running the library on.
You can probably find directions about it by typing "heroku install google chrome" on your favorite search engine.

Most of the time, installing Chrome will be enough, as HTML2Image will be able to find it itself.

---
However, if you still have an error, you can do the following:

You should then be able to run one of the following commands depending on your install :
`chrome --version`/ `google-chome --version `/ `chromium --version`

Once you assessed that Chrome is properly installed, you can run the `where chrome` command (replace `chrome` by which command works for you), it will give you the path to the Chrome executable on the current machine.

You can then give this path to html2image in your code:

```python
from html2image import Html2Image
hti = Html2Image(chrome_path='C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe')
hti.chrome_path = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'
```

**Comment by ashutoshkrris** [comment] 2021-06-08 03:37
Thanks for the response! @vgalin 
But I still could not resolve the issue. I am attaching the error that I received : 

When I didn't specify the `chrome_path`, it gave this error : 
```
Building on the Heroku-20 stack
-----> Using buildpacks:
       1. heroku/python
       2. https://github.com/heroku/heroku-buildpack-google-chrome.git
       3. https://github.com/heroku/heroku-buildpack-chromedriver.git
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Requirements file has been changed, clearing cached dependencies
-----> Installing python-3.9.5
-----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
-----> Installing dependencies with Pipenv 2020.11.15
       Installing dependencies from Pipfile.lock (bba7cf)...
-----> Installing SQLite3
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_8e9c226f/manage.py", line 22, in <module>
           main()
         File "/tmp/build_8e9c226f/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
           django.setup()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
           app_config.ready()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
           self.module.autodiscover()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
           autodiscover_modules('admin', register_to=site)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
           import_module('%s.%s' % (app_config.name, module_to_search))
         File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
         File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 855, in exec_module
         File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
         File "/tmp/build_8e9c226f/certification/admin.py", line 1, in <module>
           from certification.views import generate_contributor_badge
         File "/tmp/build_8e9c226f/certification/views.py", line 19, in <module>
           HTI = Html2Image(output_path=BADGE_PATH)
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 163, in __init__
           self.chrome_path = chrome_path
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 176, in chrome_path
           self._chrome_path = _find_chrome(value)
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 59, in _find_chrome
           version_result = subprocess.check_output(
         File "/app/.heroku/python/lib/python3.9/subprocess.py", line 424, in check_output
           return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
         File "/app/.heroku/python/lib/python3.9/subprocess.py", line 505, in run
           with Popen(*popenargs, **kwargs) as process:
         File "/app/.heroku/python/lib/python3.9/subprocess.py", line 951, in __init__
           self._execute_child(args, executable, preexec_fn, close_fds,
         File "/app/.heroku/python/lib/python3.9/subprocess.py", line 1821, in _execute_child
           raise child_exception_type(errno_num, err_msg, err_filename)
       FileNotFoundError: [Errno 2] No such file or directory: 'google-chrome'
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

After that, I ran `whereis google-chrome` and received this output : `google-chrome: /app/.apt/usr/bin/google-chrome`
So, I used that path in `chrome_path`, but then it gave this error : 

```
-----> Building on the Heroku-20 stack
-----> Using buildpacks:
       1. heroku/python
       2. https://github.com/heroku/heroku-buildpack-google-chrome.git
       3. https://github.com/heroku/heroku-buildpack-chromedriver.git
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Requirements file has been changed, clearing cached dependencies
-----> Installing python-3.9.5
-----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2
-----> Installing dependencies with Pipenv 2020.11.15
       Installing dependencies from Pipfile.lock (bba7cf)...
-----> Installing SQLite3
-----> $ python manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "/tmp/build_859ba366/manage.py", line 22, in <module>
           main()
         File "/tmp/build_859ba366/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
           django.setup()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
           apps.populate(settings.INSTALLED_APPS)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
           app_config.ready()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/admin/apps.py", line 27, in ready
           self.module.autodiscover()
         File "/app/.heroku/python/lib/python3.9/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
           autodiscover_modules('admin', register_to=site)
         File "/app/.heroku/python/lib/python3.9/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
           import_module('%s.%s' % (app_config.name, module_to_search))
         File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
         File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
         File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 855, in exec_module
         File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
         File "/tmp/build_859ba366/certification/admin.py", line 1, in <module>
           from certification.views import generate_contributor_badge
         File "/tmp/build_859ba366/certification/views.py", line 18, in <module>
           HTI = Html2Image(chrome_path='/app/.apt/usr/bin/google-chrome')
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 163, in __init__
           self.chrome_path = chrome_path
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 176, in chrome_path
           self._chrome_path = _find_chrome(value)
         File "/app/.heroku/python/lib/python3.9/site-packages/html2image/html2image.py", line 40, in _find_chrome
           raise FileNotFoundError('Could not find chrome in the given path.')
       FileNotFoundError: Could not find chrome in the given path.
 !     Error while running '$ python manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed
```

**Comment by vgalin** [comment] 2021-06-08 11:22
The last error is caused by the fact that html2image sets by default a "default background color". There is currently no way to disable it without editing the code yourself ... If you wish to do so, you'll just have to grab the html2image.py file and delete the following line:
https://github.com/vgalin/html2image/blob/e4521960f8e6c41bbe50db9a7ff4006d6e08f8ba/html2image/html2image.py#L249
Then you can put this file in your project and use it as is.

The reason I'm suggesting you this workaround is that I'm currently working on an overhaul of this piece of code and that I won't be able to quick-fix for you in the next few days.

**Comment by vgalin** [comment] 2021-06-30 21:53
Hello, the issue you had with the default flags has been fixed more or less directly by the latest version of the package, as you can now edit and overwrite default flags.

For example, to keep hiding the scrollbar but remove the default background flag, you can do the following :
```python
from html2image import Html2Image

hti = Html2Image(custom_flags=['--hide-scrollbars'])
hti.screenshot(...)
...
```

**Comment by vgalin** [comment] 2021-07-05 22:54
I'm closing this issue as it is likely resolved, feel free to reopen it if the problem presists.

**Closed by vgalin** 2021-07-05 22:54 UTC
