### ISSUE TITLE
Open multiple tabs is only supported when remote debugging is enabled

### ISSUE THREAD

**Issue by aneeshpanoli** [vgalin/html2image#40] opened 2021-09-04 19:12 UTC
```python
from html2image import Html2Image
hti = Html2Image()

hti.browser.flags = ['no-sandbox']
hti.output_path = root+'/x/'
  hti.screenshot(
    html_file=root+'/x/x.html',
    save_as='plot_'+str(i)+'.png'
)
```

1. Running without flags gives me the following error
`Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`
2. With --no-sandbox tag, I get a different error
` Open multiple tabs is only supported when remote debugging is enabled.`

Any idea how to fix this?

**Comment by vgalin** [comment] 2021-09-04 19:24
The double dash has to be present before a flag, so 
`hti.browser.flags = ['no-sandbox']` is not recognized as a flag, while `hti.browser.flags = ['--no-sandbox']` is.

I recommend you using `hti.browser.flags.append('--no-sandbox')` to keep the default flags while adding the no-sandbox flag.

Does this solve your issue?

**Comment by aneeshpanoli** [comment] 2021-09-04 19:27
@vgalin 
Thanks for the quick response.
Now I get a new error
`[0904/192602.479966:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
`

**Comment by aneeshpanoli** [comment] 2021-09-04 19:31
After that I tried adding flag `--disable-gpu` but nothing happened. However, when I remove `--` and just append `disable-gpu`, the previous waring disappeared. Now I'm back to the same error as stated before.  `Open multiple tabs is only supported when remote debugging is enabled.`

**Comment by vgalin** [comment] 2021-09-04 19:41
The `Open multiple tabs is only supported when remote debugging is enabled.` appears because if there is no `--` in front of a flag, chrome thinks that the flag is a file and tries to open it in "multi tab".

But the `Passthrough is not supported, GL is swiftshader` message is thrown by Chrome/Chromium. According to [this SO answer](https://stackoverflow.com/questions/67501093/passthrough-is-not-supported-gl-is-disabled) The `--disable-software-rasterizer` flag could also help:
`hti.browser.flags += ('--no-sandbox', '--disable-gpu', '--disable-software-rasterizer')`

Could you tell me which OS + chrome/chromium version you're using if the problem persist, so that I can try to troubleshoot it directly?

**Comment by aneeshpanoli** [comment] 2021-09-04 19:51
Thanks but didn't work.
errors out `[0904/194554.685830:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled`
I think the `disable-gpu` tag somehow works without `--`. 

```Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

chromium-browser: 92.0.4515.159

docker image: tensorflow/tensorflow:latest-gpu-jupyter
```

**Comment by vgalin** [comment] 2021-09-04 20:19
Thanks, while taking a screenshot on this image, I indeed had the same error message, but with some other lines too :
```command
root@055a40112299:/tf# python
>>> from html2image import Html2Image
>>> hti = Html2Image()
>>> hti.browser.flags += ('--no-sandbox', '--disable-gpu', '--disable-software-rasterizer')
>>> hti.screenshot(url='http://www.python.org')
[0904/200659.131629:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
[0904/200659.136438:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is disabled
[0904/200700.130437:INFO:headless_shell.cc(648)] Written to file /tf/screenshot.png.
```
And the screenshot was correctly taken (it also worked with an html file).

```
root@055a40112299:/tf# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

root@055a40112299:/tf# chromium-browser --version
Chromium 92.0.4515.159 Built on Ubuntu , running on Ubuntu 18.04
```
So in the end I wasn't able to reproduce the issue ...
I installed chromium-browser through `apt-get install chromium-browser` (preceded by an `apt-get update`).

**Comment by vgalin** [comment] 2021-09-16 21:44
I'm closing this issue as it is likely resolved, feel free to reopen it if the problem presists.

**Closed by vgalin** 2021-09-16 21:44 UTC
